# Generated by Django 2.1.3 on 2019-07-09 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=12, verbose_name='学号')),
                ('student_name', models.CharField(max_length=12, verbose_name='姓名')),
                ('student_password', models.CharField(default='ILoveEO16', max_length=20, verbose_name='密码')),
                ('academic_score_1', models.PositiveSmallIntegerField(verbose_name='前五学期专业成绩')),
                ('developmental_score_1', models.PositiveSmallIntegerField(verbose_name='前五学期发展成绩')),
                ('science_score_1', models.PositiveSmallIntegerField(verbose_name='前五学期科创成绩')),
                ('academic_score_2', models.PositiveSmallIntegerField(verbose_name='第六学期专业成绩')),
                ('developmental_score_2', models.PositiveSmallIntegerField(verbose_name='第六学期发展成绩')),
                ('science_score_2', models.PositiveSmallIntegerField(verbose_name='第六学期科创成绩')),
                ('credit', models.PositiveSmallIntegerField(verbose_name='前六学期学分')),
                ('change_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': '学生',
                'db_table': 'Student',
                'ordering': ['student_id'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(max_length=10, verbose_name='专业名称')),
                ('system_student_num', models.PositiveSmallIntegerField(verbose_name='人数')),
            ],
            options={
                'verbose_name_plural': '专业',
                'db_table': 'System',
                'ordering': ['-system_student_num'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='student_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.System', verbose_name='专业'),
        ),
    ]
