# Generated by Django 2.1.3 on 2019-07-09 09:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_ip', models.GenericIPAddressField(verbose_name='登录ip')),
                ('login_browser', models.CharField(default='未知的浏览器', max_length=30, verbose_name='浏览器')),
                ('login_system', models.CharField(default='未知的系统', max_length=30, verbose_name='操作系统')),
                ('login_device', models.CharField(default='未知的设备', max_length=30, verbose_name='设备')),
                ('login_location', models.CharField(default='未知位置', max_length=30, verbose_name='位置')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='登录时间')),
                ('login_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='score.Student', verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '访问记录',
                'db_table': 'LoginRecord',
                'ordering': ['-login_time'],
            },
        ),
    ]
