# Generated by Django 2.1.3 on 2019-07-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_loginrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_score_1',
        ),
        migrations.RemoveField(
            model_name='student',
            name='academic_score_2',
        ),
        migrations.RemoveField(
            model_name='student',
            name='credit',
        ),
        migrations.AddField(
            model_name='student',
            name='academic_score_1_5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='前5学期专业成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_score_1_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='前6学期专业成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_score_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='6学期专业成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='credit_1_5',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='前5学期学分'),
        ),
        migrations.AddField(
            model_name='student',
            name='credit_1_6',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='前6学期学分'),
        ),
        migrations.AddField(
            model_name='student',
            name='credit_6',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='第6学期学分'),
        ),
        migrations.AddField(
            model_name='student',
            name='developmental_score_3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='3学期发展成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='developmental_score_4',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='4学期发展成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='developmental_score_5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='5学期发展成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='developmental_score_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='6学期发展成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_score_3',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='3学期科创成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_score_4',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='4学期科创成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_score_5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='5学期科创成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='science_score_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='6学期科创成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='whole_score_1_5',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='前5学期综合成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='whole_score_1_6',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='前6学期综合成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='developmental_score_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='1学期发展成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='developmental_score_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='2学期发展成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_score_1',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='1学期科创成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='science_score_2',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='2学期科创成绩'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(default='', max_length=12, verbose_name='姓名'),
        ),
    ]
