# Generated by Django 2.1.3 on 2019-07-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0004_auto_20190709_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_identity',
            field=models.CharField(default='无', max_length=12, verbose_name='备注信息'),
        ),
    ]
